name: CI

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS Universal
            os: macos-latest
            cmake_args: '-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13'
            test: true
          - name: iOS
            os: macos-latest
            cmake_args: '-DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0'
            test: false
          - name: Linux GCC
            os: ubuntu-latest
            cmake_args: '-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++'
            test: true
          - name: Linux Clang
            os: ubuntu-latest
            cmake_args: '-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++'
            test: true
          - name: Windows Clang
            os: windows-latest
            cmake_args: '-DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl'
            test: false
            msvc_env: true
          - name: Windows MSVC
            os: windows-latest
            cmake_args: '-DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl'
            test: false
            msvc_env: true

    steps:
      - uses: actions/checkout@v4

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - if: matrix.msvc_env
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake -G Ninja -S . -B build ${{ matrix.cmake_args }}

      - name: Build
        run: cmake --build build

      - if: matrix.test
        name: Test
        run: ctest --test-dir build --output-on-failure
